# 워크플로우 이름
name: Github Actions 실행시켜보기

# 워크플로우 실행 조건
# main 브랜치에 push 이벤트가 발생하면 워크플로우 실행
on:
  push:
    branches:
      - main

# 워크플로우 실행 작업
# 하나의 워크플로우는 1개 이상의 JOB으로 구성됩니다.
# 여러 job은 병렬로 실행됩니다.
jobs:
  # job을 식별하기 위한 id
  My-Deploy-Job:
    # ubuntu 환경/ 가장 최신 버전(latest)
    runs-on: ubuntu-latest

    # Step : 특정 작업을 수행하는 가장 작은 단위
    steps:
      # step 이름
      - name: Hrllo world 찍기
        # step 실행 명령어
        run: echo "Hello, World!"

      - name: 여러 명령어 문장 작성하기
        run: |
          echo "Good"
          echo "Morning"
